package org.campus.model;

import java.util.Date;

public class Category {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_category.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_category.CategoryName
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String categoryname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_category.NamePinYin
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String namepinyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_category.NameFirstLetter
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String namefirstletter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_category.OrderBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Integer orderby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_category.VersionNumber
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String versionnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_category.IsActive
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Integer isactive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_category.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_category.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_category.LastUpdateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String lastupdateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_category.LastUpdateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Date lastupdatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_category.UID
     *
     * @return the value of ts_sys_category.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_category.UID
     *
     * @param uid the value for ts_sys_category.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_category.CategoryName
     *
     * @return the value of ts_sys_category.CategoryName
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getCategoryname() {
        return categoryname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_category.CategoryName
     *
     * @param categoryname the value for ts_sys_category.CategoryName
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCategoryname(String categoryname) {
        this.categoryname = categoryname == null ? null : categoryname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_category.NamePinYin
     *
     * @return the value of ts_sys_category.NamePinYin
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getNamepinyin() {
        return namepinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_category.NamePinYin
     *
     * @param namepinyin the value for ts_sys_category.NamePinYin
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setNamepinyin(String namepinyin) {
        this.namepinyin = namepinyin == null ? null : namepinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_category.NameFirstLetter
     *
     * @return the value of ts_sys_category.NameFirstLetter
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getNamefirstletter() {
        return namefirstletter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_category.NameFirstLetter
     *
     * @param namefirstletter the value for ts_sys_category.NameFirstLetter
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setNamefirstletter(String namefirstletter) {
        this.namefirstletter = namefirstletter == null ? null : namefirstletter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_category.OrderBy
     *
     * @return the value of ts_sys_category.OrderBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Integer getOrderby() {
        return orderby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_category.OrderBy
     *
     * @param orderby the value for ts_sys_category.OrderBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setOrderby(Integer orderby) {
        this.orderby = orderby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_category.VersionNumber
     *
     * @return the value of ts_sys_category.VersionNumber
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getVersionnumber() {
        return versionnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_category.VersionNumber
     *
     * @param versionnumber the value for ts_sys_category.VersionNumber
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setVersionnumber(String versionnumber) {
        this.versionnumber = versionnumber == null ? null : versionnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_category.IsActive
     *
     * @return the value of ts_sys_category.IsActive
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Integer getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_category.IsActive
     *
     * @param isactive the value for ts_sys_category.IsActive
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setIsactive(Integer isactive) {
        this.isactive = isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_category.CreateBy
     *
     * @return the value of ts_sys_category.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_category.CreateBy
     *
     * @param createby the value for ts_sys_category.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_category.CreateDate
     *
     * @return the value of ts_sys_category.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_category.CreateDate
     *
     * @param createdate the value for ts_sys_category.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_category.LastUpdateBy
     *
     * @return the value of ts_sys_category.LastUpdateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getLastupdateby() {
        return lastupdateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_category.LastUpdateBy
     *
     * @param lastupdateby the value for ts_sys_category.LastUpdateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setLastupdateby(String lastupdateby) {
        this.lastupdateby = lastupdateby == null ? null : lastupdateby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_category.LastUpdateDate
     *
     * @return the value of ts_sys_category.LastUpdateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Date getLastupdatedate() {
        return lastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_category.LastUpdateDate
     *
     * @param lastupdatedate the value for ts_sys_category.LastUpdateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setLastupdatedate(Date lastupdatedate) {
        this.lastupdatedate = lastupdatedate;
    }
}