package org.campus.model;

import java.util.Date;

import org.campus.model.enums.ActiveType;
import org.campus.model.enums.AnonymousType;
import org.campus.model.enums.TypeCode;

public class Comment {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ts_app_comment.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_comment.SourceUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String sourceuid;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_comment.ComUserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String comuseruid;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_comment.UserNickName
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String usernickname;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_comment.ObjUserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String objuseruid;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_comment.ObjUserNickName
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String objusernickname;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_comment.CommentContent
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String commentcontent;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_comment.TypeCode
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private TypeCode typecode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_comment.isActive
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private ActiveType isactive;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_comment.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_comment.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_comment.LastUpdateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String lastupdateby;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_comment.LastUpdateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Date lastupdatedate;

    private String ipaddress;

    private String objComment;

    private String srcPostId;

    private AnonymousType isAnonymous;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_comment.UID
     *
     * @return the value of ts_app_comment.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_comment.UID
     *
     * @param uid the value for ts_app_comment.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_comment.SourceUID
     *
     * @return the value of ts_app_comment.SourceUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getSourceuid() {
        return sourceuid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_comment.SourceUID
     *
     * @param sourceuid the value for ts_app_comment.SourceUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setSourceuid(String sourceuid) {
        this.sourceuid = sourceuid == null ? null : sourceuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_comment.ComUserUID
     *
     * @return the value of ts_app_comment.ComUserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getComuseruid() {
        return comuseruid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_comment.ComUserUID
     *
     * @param comuseruid the value for ts_app_comment.ComUserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setComuseruid(String comuseruid) {
        this.comuseruid = comuseruid == null ? null : comuseruid.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_comment.UserNickName
     *
     * @return the value of ts_app_comment.UserNickName
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getUsernickname() {
        return usernickname;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_comment.UserNickName
     *
     * @param usernickname the value for ts_app_comment.UserNickName
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setUsernickname(String usernickname) {
        this.usernickname = usernickname == null ? null : usernickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_comment.ObjUserUID
     *
     * @return the value of ts_app_comment.ObjUserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getObjuseruid() {
        return objuseruid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_comment.ObjUserUID
     *
     * @param objuseruid the value for ts_app_comment.ObjUserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setObjuseruid(String objuseruid) {
        this.objuseruid = objuseruid == null ? null : objuseruid.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_comment.ObjUserNickName
     *
     * @return the value of ts_app_comment.ObjUserNickName
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getObjusernickname() {
        return objusernickname;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_comment.ObjUserNickName
     *
     * @param objusernickname the value for ts_app_comment.ObjUserNickName
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setObjusernickname(String objusernickname) {
        this.objusernickname = objusernickname == null ? null : objusernickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_comment.CommentContent
     *
     * @return the value of ts_app_comment.CommentContent
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getCommentcontent() {
        return commentcontent;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_comment.CommentContent
     *
     * @param commentcontent the value for ts_app_comment.CommentContent
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCommentcontent(String commentcontent) {
        this.commentcontent = commentcontent == null ? null : commentcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_comment.TypeCode
     *
     * @return the value of ts_app_comment.TypeCode
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public TypeCode getTypecode() {
        return typecode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_comment.TypeCode
     *
     * @param typecode the value for ts_app_comment.TypeCode
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setTypecode(TypeCode typecode) {
        this.typecode = typecode;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_comment.isActive
     *
     * @return the value of ts_app_comment.isActive
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public ActiveType getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_comment.isActive
     *
     * @param isactive the value for ts_app_comment.isActive
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setIsactive(ActiveType isactive) {
        this.isactive = isactive;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_comment.CreateBy
     *
     * @return the value of ts_app_comment.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_comment.CreateBy
     *
     * @param createby the value for ts_app_comment.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_comment.CreateDate
     *
     * @return the value of ts_app_comment.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_comment.CreateDate
     *
     * @param createdate the value for ts_app_comment.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_comment.LastUpdateBy
     *
     * @return the value of ts_app_comment.LastUpdateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getLastupdateby() {
        return lastupdateby;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_comment.LastUpdateBy
     *
     * @param lastupdateby the value for ts_app_comment.LastUpdateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setLastupdateby(String lastupdateby) {
        this.lastupdateby = lastupdateby == null ? null : lastupdateby.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_comment.LastUpdateDate
     *
     * @return the value of ts_app_comment.LastUpdateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Date getLastupdatedate() {
        return lastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_comment.LastUpdateDate
     *
     * @param lastupdatedate the value for ts_app_comment.LastUpdateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setLastupdatedate(Date lastupdatedate) {
        this.lastupdatedate = lastupdatedate;
    }

    public String getIpaddress() {
        return ipaddress;
    }

    public void setIpaddress(String ipaddress) {
        this.ipaddress = ipaddress;
    }

    public String getObjComment() {
        return objComment;
    }

    public void setObjComment(String objComment) {
        this.objComment = objComment;
    }

    public String getSrcPostId() {
        return srcPostId;
    }

    public void setSrcPostId(String srcPostId) {
        this.srcPostId = srcPostId;
    }

    public AnonymousType getIsAnonymous() {
        return isAnonymous;
    }

    public void setIsAnonymous(AnonymousType isAnonymous) {
        this.isAnonymous = isAnonymous;
    }

}