package org.campus.model;

import java.util.Date;

public class Complain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_complain.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_complain.SourceUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String sourceuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_complain.UserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String useruid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_complain.ComplainDesc
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String complaindesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_complain.TypeCode
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Integer typecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_complain.ManageOperate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Integer manageoperate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_complain.OperateUserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String operateuseruid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_complain.OperateTime
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Date operatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_complain.IsActive
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Integer isactive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_complain.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_complain.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_complain.LastUpdateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String lastupdateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_complain.LastUpdateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Date lastupdatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_complain.UID
     *
     * @return the value of ts_app_complain.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_complain.UID
     *
     * @param uid the value for ts_app_complain.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_complain.SourceUID
     *
     * @return the value of ts_app_complain.SourceUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getSourceuid() {
        return sourceuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_complain.SourceUID
     *
     * @param sourceuid the value for ts_app_complain.SourceUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setSourceuid(String sourceuid) {
        this.sourceuid = sourceuid == null ? null : sourceuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_complain.UserUID
     *
     * @return the value of ts_app_complain.UserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getUseruid() {
        return useruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_complain.UserUID
     *
     * @param useruid the value for ts_app_complain.UserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setUseruid(String useruid) {
        this.useruid = useruid == null ? null : useruid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_complain.ComplainDesc
     *
     * @return the value of ts_app_complain.ComplainDesc
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getComplaindesc() {
        return complaindesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_complain.ComplainDesc
     *
     * @param complaindesc the value for ts_app_complain.ComplainDesc
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setComplaindesc(String complaindesc) {
        this.complaindesc = complaindesc == null ? null : complaindesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_complain.TypeCode
     *
     * @return the value of ts_app_complain.TypeCode
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Integer getTypecode() {
        return typecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_complain.TypeCode
     *
     * @param typecode the value for ts_app_complain.TypeCode
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setTypecode(Integer typecode) {
        this.typecode = typecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_complain.ManageOperate
     *
     * @return the value of ts_app_complain.ManageOperate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Integer getManageoperate() {
        return manageoperate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_complain.ManageOperate
     *
     * @param manageoperate the value for ts_app_complain.ManageOperate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setManageoperate(Integer manageoperate) {
        this.manageoperate = manageoperate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_complain.OperateUserUID
     *
     * @return the value of ts_app_complain.OperateUserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getOperateuseruid() {
        return operateuseruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_complain.OperateUserUID
     *
     * @param operateuseruid the value for ts_app_complain.OperateUserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setOperateuseruid(String operateuseruid) {
        this.operateuseruid = operateuseruid == null ? null : operateuseruid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_complain.OperateTime
     *
     * @return the value of ts_app_complain.OperateTime
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Date getOperatetime() {
        return operatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_complain.OperateTime
     *
     * @param operatetime the value for ts_app_complain.OperateTime
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setOperatetime(Date operatetime) {
        this.operatetime = operatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_complain.IsActive
     *
     * @return the value of ts_app_complain.IsActive
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Integer getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_complain.IsActive
     *
     * @param isactive the value for ts_app_complain.IsActive
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setIsactive(Integer isactive) {
        this.isactive = isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_complain.CreateBy
     *
     * @return the value of ts_app_complain.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_complain.CreateBy
     *
     * @param createby the value for ts_app_complain.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_complain.CreateDate
     *
     * @return the value of ts_app_complain.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_complain.CreateDate
     *
     * @param createdate the value for ts_app_complain.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_complain.LastUpdateBy
     *
     * @return the value of ts_app_complain.LastUpdateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getLastupdateby() {
        return lastupdateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_complain.LastUpdateBy
     *
     * @param lastupdateby the value for ts_app_complain.LastUpdateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setLastupdateby(String lastupdateby) {
        this.lastupdateby = lastupdateby == null ? null : lastupdateby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_complain.LastUpdateDate
     *
     * @return the value of ts_app_complain.LastUpdateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Date getLastupdatedate() {
        return lastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_complain.LastUpdateDate
     *
     * @param lastupdatedate the value for ts_app_complain.LastUpdateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setLastupdatedate(Date lastupdatedate) {
        this.lastupdatedate = lastupdatedate;
    }
}