package org.campus.model;

import java.util.Date;

import org.campus.model.enums.CheckType;

public class FreshNewsAudit {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_freshnews_audit.UID
     *
     * @mbggenerated Tue Aug 25 22:13:56 CST 2015
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_freshnews_audit.UserId
     *
     * @mbggenerated Tue Aug 25 22:13:56 CST 2015
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_freshnews_audit.PostId
     *
     * @mbggenerated Tue Aug 25 22:13:56 CST 2015
     */
    private String postid;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_freshnews_audit.AuditReust
     *
     * @mbggenerated Tue Aug 25 22:13:56 CST 2015
     */
    private CheckType auditreust;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_freshnews_audit.AuditTime
     *
     * @mbggenerated Tue Aug 25 22:13:56 CST 2015
     */
    private Date audittime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_freshnews_audit.UID
     *
     * @return the value of ts_app_freshnews_audit.UID
     *
     * @mbggenerated Tue Aug 25 22:13:56 CST 2015
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_freshnews_audit.UID
     *
     * @param uid the value for ts_app_freshnews_audit.UID
     *
     * @mbggenerated Tue Aug 25 22:13:56 CST 2015
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_freshnews_audit.UserId
     *
     * @return the value of ts_app_freshnews_audit.UserId
     *
     * @mbggenerated Tue Aug 25 22:13:56 CST 2015
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_freshnews_audit.UserId
     *
     * @param userid the value for ts_app_freshnews_audit.UserId
     *
     * @mbggenerated Tue Aug 25 22:13:56 CST 2015
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_freshnews_audit.PostId
     *
     * @return the value of ts_app_freshnews_audit.PostId
     *
     * @mbggenerated Tue Aug 25 22:13:56 CST 2015
     */
    public String getPostid() {
        return postid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_freshnews_audit.PostId
     *
     * @param postid the value for ts_app_freshnews_audit.PostId
     *
     * @mbggenerated Tue Aug 25 22:13:56 CST 2015
     */
    public void setPostid(String postid) {
        this.postid = postid == null ? null : postid.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_freshnews_audit.AuditReust
     *
     * @return the value of ts_app_freshnews_audit.AuditReust
     *
     * @mbggenerated Tue Aug 25 22:13:56 CST 2015
     */
    public CheckType getAuditreust() {
        return auditreust;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_freshnews_audit.AuditReust
     *
     * @param auditreust the value for ts_app_freshnews_audit.AuditReust
     *
     * @mbggenerated Tue Aug 25 22:13:56 CST 2015
     */
    public void setAuditreust(CheckType auditreust) {
        this.auditreust = auditreust;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_freshnews_audit.AuditTime
     *
     * @return the value of ts_app_freshnews_audit.AuditTime
     *
     * @mbggenerated Tue Aug 25 22:13:56 CST 2015
     */
    public Date getAudittime() {
        return audittime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_freshnews_audit.AuditTime
     *
     * @param audittime the value for ts_app_freshnews_audit.AuditTime
     *
     * @mbggenerated Tue Aug 25 22:13:56 CST 2015
     */
    public void setAudittime(Date audittime) {
        this.audittime = audittime;
    }
}