package org.campus.model;

import java.util.Date;

public class GroupUsers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_groupusers.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_groupusers.GroupUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String groupuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_groupusers.UserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String useruid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_groupusers.IsLeader
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Integer isleader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_groupusers.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_groupusers.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_groupusers.IsActive
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Integer isactive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_groupusers.LastUpdateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String lastupdateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_groupusers.LastUpdateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Date lastupdatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_groupusers.UID
     *
     * @return the value of ts_app_groupusers.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_groupusers.UID
     *
     * @param uid the value for ts_app_groupusers.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_groupusers.GroupUID
     *
     * @return the value of ts_app_groupusers.GroupUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getGroupuid() {
        return groupuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_groupusers.GroupUID
     *
     * @param groupuid the value for ts_app_groupusers.GroupUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setGroupuid(String groupuid) {
        this.groupuid = groupuid == null ? null : groupuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_groupusers.UserUID
     *
     * @return the value of ts_app_groupusers.UserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getUseruid() {
        return useruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_groupusers.UserUID
     *
     * @param useruid the value for ts_app_groupusers.UserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setUseruid(String useruid) {
        this.useruid = useruid == null ? null : useruid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_groupusers.IsLeader
     *
     * @return the value of ts_app_groupusers.IsLeader
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Integer getIsleader() {
        return isleader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_groupusers.IsLeader
     *
     * @param isleader the value for ts_app_groupusers.IsLeader
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setIsleader(Integer isleader) {
        this.isleader = isleader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_groupusers.CreateBy
     *
     * @return the value of ts_app_groupusers.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_groupusers.CreateBy
     *
     * @param createby the value for ts_app_groupusers.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_groupusers.CreateDate
     *
     * @return the value of ts_app_groupusers.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_groupusers.CreateDate
     *
     * @param createdate the value for ts_app_groupusers.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_groupusers.IsActive
     *
     * @return the value of ts_app_groupusers.IsActive
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Integer getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_groupusers.IsActive
     *
     * @param isactive the value for ts_app_groupusers.IsActive
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setIsactive(Integer isactive) {
        this.isactive = isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_groupusers.LastUpdateBy
     *
     * @return the value of ts_app_groupusers.LastUpdateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getLastupdateby() {
        return lastupdateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_groupusers.LastUpdateBy
     *
     * @param lastupdateby the value for ts_app_groupusers.LastUpdateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setLastupdateby(String lastupdateby) {
        this.lastupdateby = lastupdateby == null ? null : lastupdateby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_groupusers.LastUpdateDate
     *
     * @return the value of ts_app_groupusers.LastUpdateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Date getLastupdatedate() {
        return lastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_groupusers.LastUpdateDate
     *
     * @param lastupdatedate the value for ts_app_groupusers.LastUpdateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setLastupdatedate(Date lastupdatedate) {
        this.lastupdatedate = lastupdatedate;
    }
}