package org.campus.model;

import java.util.Date;

public class Install {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ts_app_install.UID
     *
     * @mbggenerated Tue Aug 25 23:41:54 CST 2015
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_install.Source
     *
     * @mbggenerated Tue Aug 25 23:41:54 CST 2015
     */
    private String source;

    private String sourceName;

    private int count;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_install.CreateDate
     *
     * @mbggenerated Tue Aug 25 23:41:54 CST 2015
     */
    private Date createdate;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_install.UID
     *
     * @return the value of ts_app_install.UID
     *
     * @mbggenerated Tue Aug 25 23:41:54 CST 2015
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_install.UID
     *
     * @param uid the value for ts_app_install.UID
     *
     * @mbggenerated Tue Aug 25 23:41:54 CST 2015
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_install.Source
     *
     * @return the value of ts_app_install.Source
     *
     * @mbggenerated Tue Aug 25 23:41:54 CST 2015
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_install.Source
     *
     * @param source the value for ts_app_install.Source
     *
     * @mbggenerated Tue Aug 25 23:41:54 CST 2015
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    public String getSourceName() {
        return sourceName;
    }

    public void setSourceName(String sourceName) {
        this.sourceName = sourceName;
    }

    public int getCount() {
        return count;
    }

    public void setCount(int count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_install.CreateDate
     *
     * @return the value of ts_app_install.CreateDate
     *
     * @mbggenerated Tue Aug 25 23:41:54 CST 2015
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_install.CreateDate
     *
     * @param createdate the value for ts_app_install.CreateDate
     *
     * @mbggenerated Tue Aug 25 23:41:54 CST 2015
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}