package org.campus.model;

import java.util.Date;

public class Integral {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_integral.UID
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_integral.IntegralType
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    private String integraltype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_integral.IntegralTime
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    private Date integraltime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_integral.UserId
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_integral.IntegralIncome
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    private Long integralincome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_integral.IntegralExpend
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    private Long integralexpend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_integral.IntegralBalance
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    private Long integralbalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_integral.Remark
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_integral.UID
     *
     * @return the value of ts_app_integral.UID
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_integral.UID
     *
     * @param uid the value for ts_app_integral.UID
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_integral.IntegralType
     *
     * @return the value of ts_app_integral.IntegralType
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    public String getIntegraltype() {
        return integraltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_integral.IntegralType
     *
     * @param integraltype the value for ts_app_integral.IntegralType
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    public void setIntegraltype(String integraltype) {
        this.integraltype = integraltype == null ? null : integraltype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_integral.IntegralTime
     *
     * @return the value of ts_app_integral.IntegralTime
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    public Date getIntegraltime() {
        return integraltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_integral.IntegralTime
     *
     * @param integraltime the value for ts_app_integral.IntegralTime
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    public void setIntegraltime(Date integraltime) {
        this.integraltime = integraltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_integral.UserId
     *
     * @return the value of ts_app_integral.UserId
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_integral.UserId
     *
     * @param userid the value for ts_app_integral.UserId
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_integral.IntegralIncome
     *
     * @return the value of ts_app_integral.IntegralIncome
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    public Long getIntegralincome() {
        return integralincome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_integral.IntegralIncome
     *
     * @param integralincome the value for ts_app_integral.IntegralIncome
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    public void setIntegralincome(Long integralincome) {
        this.integralincome = integralincome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_integral.IntegralExpend
     *
     * @return the value of ts_app_integral.IntegralExpend
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    public Long getIntegralexpend() {
        return integralexpend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_integral.IntegralExpend
     *
     * @param integralexpend the value for ts_app_integral.IntegralExpend
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    public void setIntegralexpend(Long integralexpend) {
        this.integralexpend = integralexpend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_integral.IntegralBalance
     *
     * @return the value of ts_app_integral.IntegralBalance
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    public Long getIntegralbalance() {
        return integralbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_integral.IntegralBalance
     *
     * @param integralbalance the value for ts_app_integral.IntegralBalance
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    public void setIntegralbalance(Long integralbalance) {
        this.integralbalance = integralbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_integral.Remark
     *
     * @return the value of ts_app_integral.Remark
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_integral.Remark
     *
     * @param remark the value for ts_app_integral.Remark
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}