package org.campus.model;

import java.util.Date;

public class Log {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tl_log.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tl_log.Thread
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Integer thread;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tl_log.Level
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tl_log.Message
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tl_log.CustomMessage
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String custommessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tl_log.Exception
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String exception;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tl_log.ClassName
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String classname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tl_log.ModuleName
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String modulename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tl_log.MehodName
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String mehodname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tl_log.IsActive
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Integer isactive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tl_log.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tl_log.Date
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tl_log.LogID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String logid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_log.UID
     *
     * @return the value of tl_log.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_log.UID
     *
     * @param uid the value for tl_log.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_log.Thread
     *
     * @return the value of tl_log.Thread
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Integer getThread() {
        return thread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_log.Thread
     *
     * @param thread the value for tl_log.Thread
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setThread(Integer thread) {
        this.thread = thread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_log.Level
     *
     * @return the value of tl_log.Level
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_log.Level
     *
     * @param level the value for tl_log.Level
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_log.Message
     *
     * @return the value of tl_log.Message
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_log.Message
     *
     * @param message the value for tl_log.Message
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_log.CustomMessage
     *
     * @return the value of tl_log.CustomMessage
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getCustommessage() {
        return custommessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_log.CustomMessage
     *
     * @param custommessage the value for tl_log.CustomMessage
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCustommessage(String custommessage) {
        this.custommessage = custommessage == null ? null : custommessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_log.Exception
     *
     * @return the value of tl_log.Exception
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getException() {
        return exception;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_log.Exception
     *
     * @param exception the value for tl_log.Exception
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setException(String exception) {
        this.exception = exception == null ? null : exception.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_log.ClassName
     *
     * @return the value of tl_log.ClassName
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getClassname() {
        return classname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_log.ClassName
     *
     * @param classname the value for tl_log.ClassName
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setClassname(String classname) {
        this.classname = classname == null ? null : classname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_log.ModuleName
     *
     * @return the value of tl_log.ModuleName
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getModulename() {
        return modulename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_log.ModuleName
     *
     * @param modulename the value for tl_log.ModuleName
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setModulename(String modulename) {
        this.modulename = modulename == null ? null : modulename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_log.MehodName
     *
     * @return the value of tl_log.MehodName
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getMehodname() {
        return mehodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_log.MehodName
     *
     * @param mehodname the value for tl_log.MehodName
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setMehodname(String mehodname) {
        this.mehodname = mehodname == null ? null : mehodname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_log.IsActive
     *
     * @return the value of tl_log.IsActive
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Integer getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_log.IsActive
     *
     * @param isactive the value for tl_log.IsActive
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setIsactive(Integer isactive) {
        this.isactive = isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_log.CreateBy
     *
     * @return the value of tl_log.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_log.CreateBy
     *
     * @param createby the value for tl_log.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_log.Date
     *
     * @return the value of tl_log.Date
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_log.Date
     *
     * @param date the value for tl_log.Date
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tl_log.LogID
     *
     * @return the value of tl_log.LogID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getLogid() {
        return logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tl_log.LogID
     *
     * @param logid the value for tl_log.LogID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setLogid(String logid) {
        this.logid = logid == null ? null : logid.trim();
    }
}