package org.campus.model;

import java.util.Date;

public class LogType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_logtype.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_logtype.LogTypeCode
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String logtypecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_logtype.LogTypeName
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String logtypename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_logtype.IsActive
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Integer isactive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_logtype.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_logtype.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_logtype.LastUpdateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String lastupdateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_logtype.LastUpdateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Date lastupdatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_logtype.UID
     *
     * @return the value of ts_sys_logtype.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_logtype.UID
     *
     * @param uid the value for ts_sys_logtype.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_logtype.LogTypeCode
     *
     * @return the value of ts_sys_logtype.LogTypeCode
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getLogtypecode() {
        return logtypecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_logtype.LogTypeCode
     *
     * @param logtypecode the value for ts_sys_logtype.LogTypeCode
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setLogtypecode(String logtypecode) {
        this.logtypecode = logtypecode == null ? null : logtypecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_logtype.LogTypeName
     *
     * @return the value of ts_sys_logtype.LogTypeName
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getLogtypename() {
        return logtypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_logtype.LogTypeName
     *
     * @param logtypename the value for ts_sys_logtype.LogTypeName
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setLogtypename(String logtypename) {
        this.logtypename = logtypename == null ? null : logtypename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_logtype.IsActive
     *
     * @return the value of ts_sys_logtype.IsActive
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Integer getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_logtype.IsActive
     *
     * @param isactive the value for ts_sys_logtype.IsActive
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setIsactive(Integer isactive) {
        this.isactive = isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_logtype.CreateBy
     *
     * @return the value of ts_sys_logtype.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_logtype.CreateBy
     *
     * @param createby the value for ts_sys_logtype.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_logtype.CreateDate
     *
     * @return the value of ts_sys_logtype.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_logtype.CreateDate
     *
     * @param createdate the value for ts_sys_logtype.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_logtype.LastUpdateBy
     *
     * @return the value of ts_sys_logtype.LastUpdateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getLastupdateby() {
        return lastupdateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_logtype.LastUpdateBy
     *
     * @param lastupdateby the value for ts_sys_logtype.LastUpdateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setLastupdateby(String lastupdateby) {
        this.lastupdateby = lastupdateby == null ? null : lastupdateby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_logtype.LastUpdateDate
     *
     * @return the value of ts_sys_logtype.LastUpdateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Date getLastupdatedate() {
        return lastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_logtype.LastUpdateDate
     *
     * @param lastupdatedate the value for ts_sys_logtype.LastUpdateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setLastupdatedate(Date lastupdatedate) {
        this.lastupdatedate = lastupdatedate;
    }
}