package org.campus.model;

import java.util.Date;

public class Menu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_menu.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_menu.MenuCode
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String menucode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_menu.MenuName
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String menuname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_menu.ParentUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String parentuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_menu.MenuUrl
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String menuurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_menu.Orderby
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Integer orderby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_menu.IsShow
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Integer isshow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_menu.IsActive
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Integer isactive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_menu.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_menu.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_menu.LastUpdateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String lastupdateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_menu.LastUpdateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Date lastupdatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_menu.UID
     *
     * @return the value of ts_sys_menu.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_menu.UID
     *
     * @param uid the value for ts_sys_menu.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_menu.MenuCode
     *
     * @return the value of ts_sys_menu.MenuCode
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getMenucode() {
        return menucode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_menu.MenuCode
     *
     * @param menucode the value for ts_sys_menu.MenuCode
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setMenucode(String menucode) {
        this.menucode = menucode == null ? null : menucode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_menu.MenuName
     *
     * @return the value of ts_sys_menu.MenuName
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getMenuname() {
        return menuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_menu.MenuName
     *
     * @param menuname the value for ts_sys_menu.MenuName
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setMenuname(String menuname) {
        this.menuname = menuname == null ? null : menuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_menu.ParentUID
     *
     * @return the value of ts_sys_menu.ParentUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getParentuid() {
        return parentuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_menu.ParentUID
     *
     * @param parentuid the value for ts_sys_menu.ParentUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setParentuid(String parentuid) {
        this.parentuid = parentuid == null ? null : parentuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_menu.MenuUrl
     *
     * @return the value of ts_sys_menu.MenuUrl
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getMenuurl() {
        return menuurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_menu.MenuUrl
     *
     * @param menuurl the value for ts_sys_menu.MenuUrl
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setMenuurl(String menuurl) {
        this.menuurl = menuurl == null ? null : menuurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_menu.Orderby
     *
     * @return the value of ts_sys_menu.Orderby
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Integer getOrderby() {
        return orderby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_menu.Orderby
     *
     * @param orderby the value for ts_sys_menu.Orderby
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setOrderby(Integer orderby) {
        this.orderby = orderby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_menu.IsShow
     *
     * @return the value of ts_sys_menu.IsShow
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Integer getIsshow() {
        return isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_menu.IsShow
     *
     * @param isshow the value for ts_sys_menu.IsShow
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setIsshow(Integer isshow) {
        this.isshow = isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_menu.IsActive
     *
     * @return the value of ts_sys_menu.IsActive
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Integer getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_menu.IsActive
     *
     * @param isactive the value for ts_sys_menu.IsActive
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setIsactive(Integer isactive) {
        this.isactive = isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_menu.CreateBy
     *
     * @return the value of ts_sys_menu.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_menu.CreateBy
     *
     * @param createby the value for ts_sys_menu.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_menu.CreateDate
     *
     * @return the value of ts_sys_menu.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_menu.CreateDate
     *
     * @param createdate the value for ts_sys_menu.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_menu.LastUpdateBy
     *
     * @return the value of ts_sys_menu.LastUpdateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getLastupdateby() {
        return lastupdateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_menu.LastUpdateBy
     *
     * @param lastupdateby the value for ts_sys_menu.LastUpdateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setLastupdateby(String lastupdateby) {
        this.lastupdateby = lastupdateby == null ? null : lastupdateby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_menu.LastUpdateDate
     *
     * @return the value of ts_sys_menu.LastUpdateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Date getLastupdatedate() {
        return lastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_menu.LastUpdateDate
     *
     * @param lastupdatedate the value for ts_sys_menu.LastUpdateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setLastupdatedate(Date lastupdatedate) {
        this.lastupdatedate = lastupdatedate;
    }
}