package org.campus.model;

import java.util.Date;

public class MessageGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_messagegroup.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_messagegroup.GroupName
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String groupname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_messagegroup.GourpPic
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String gourppic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_messagegroup.CreateUserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String createuseruid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_messagegroup.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_messagegroup.IsActive
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Integer isactive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_messagegroup.LastUpdateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String lastupdateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_messagegroup.LastUpdateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Date lastupdatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_messagegroup.UID
     *
     * @return the value of ts_app_messagegroup.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_messagegroup.UID
     *
     * @param uid the value for ts_app_messagegroup.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_messagegroup.GroupName
     *
     * @return the value of ts_app_messagegroup.GroupName
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_messagegroup.GroupName
     *
     * @param groupname the value for ts_app_messagegroup.GroupName
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname == null ? null : groupname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_messagegroup.GourpPic
     *
     * @return the value of ts_app_messagegroup.GourpPic
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getGourppic() {
        return gourppic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_messagegroup.GourpPic
     *
     * @param gourppic the value for ts_app_messagegroup.GourpPic
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setGourppic(String gourppic) {
        this.gourppic = gourppic == null ? null : gourppic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_messagegroup.CreateUserUID
     *
     * @return the value of ts_app_messagegroup.CreateUserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getCreateuseruid() {
        return createuseruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_messagegroup.CreateUserUID
     *
     * @param createuseruid the value for ts_app_messagegroup.CreateUserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCreateuseruid(String createuseruid) {
        this.createuseruid = createuseruid == null ? null : createuseruid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_messagegroup.CreateDate
     *
     * @return the value of ts_app_messagegroup.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_messagegroup.CreateDate
     *
     * @param createdate the value for ts_app_messagegroup.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_messagegroup.IsActive
     *
     * @return the value of ts_app_messagegroup.IsActive
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Integer getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_messagegroup.IsActive
     *
     * @param isactive the value for ts_app_messagegroup.IsActive
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setIsactive(Integer isactive) {
        this.isactive = isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_messagegroup.LastUpdateBy
     *
     * @return the value of ts_app_messagegroup.LastUpdateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getLastupdateby() {
        return lastupdateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_messagegroup.LastUpdateBy
     *
     * @param lastupdateby the value for ts_app_messagegroup.LastUpdateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setLastupdateby(String lastupdateby) {
        this.lastupdateby = lastupdateby == null ? null : lastupdateby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_messagegroup.LastUpdateDate
     *
     * @return the value of ts_app_messagegroup.LastUpdateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Date getLastupdatedate() {
        return lastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_messagegroup.LastUpdateDate
     *
     * @param lastupdatedate the value for ts_app_messagegroup.LastUpdateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setLastupdatedate(Date lastupdatedate) {
        this.lastupdatedate = lastupdatedate;
    }
}