package org.campus.model;

import org.campus.config.SystemConfig;

public class NickName {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ts_app_nickname.UID
     *
     * @mbggenerated Thu Aug 13 16:29:19 CST 2015
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_nickname.NickName
     *
     * @mbggenerated Thu Aug 13 16:29:19 CST 2015
     */
    private String nickname = SystemConfig.getString("DEFAULT_NICK_NAME");

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_nickname.UID
     *
     * @return the value of ts_app_nickname.UID
     *
     * @mbggenerated Thu Aug 13 16:29:19 CST 2015
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_nickname.UID
     *
     * @param uid the value for ts_app_nickname.UID
     *
     * @mbggenerated Thu Aug 13 16:29:19 CST 2015
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_nickname.NickName
     *
     * @return the value of ts_app_nickname.NickName
     *
     * @mbggenerated Thu Aug 13 16:29:19 CST 2015
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_nickname.NickName
     *
     * @param nickname the value for ts_app_nickname.NickName
     *
     * @mbggenerated Thu Aug 13 16:29:19 CST 2015
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }
}