package org.campus.model;

import java.util.Date;

public class OperateLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_operatelog.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_operatelog.OperateUserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String operateuseruid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_operatelog.LogTypeUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String logtypeuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_operatelog.OperateTime
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Date operatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_operatelog.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_operatelog.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Date createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_operatelog.UID
     *
     * @return the value of ts_sys_operatelog.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_operatelog.UID
     *
     * @param uid the value for ts_sys_operatelog.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_operatelog.OperateUserUID
     *
     * @return the value of ts_sys_operatelog.OperateUserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getOperateuseruid() {
        return operateuseruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_operatelog.OperateUserUID
     *
     * @param operateuseruid the value for ts_sys_operatelog.OperateUserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setOperateuseruid(String operateuseruid) {
        this.operateuseruid = operateuseruid == null ? null : operateuseruid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_operatelog.LogTypeUID
     *
     * @return the value of ts_sys_operatelog.LogTypeUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getLogtypeuid() {
        return logtypeuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_operatelog.LogTypeUID
     *
     * @param logtypeuid the value for ts_sys_operatelog.LogTypeUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setLogtypeuid(String logtypeuid) {
        this.logtypeuid = logtypeuid == null ? null : logtypeuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_operatelog.OperateTime
     *
     * @return the value of ts_sys_operatelog.OperateTime
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Date getOperatetime() {
        return operatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_operatelog.OperateTime
     *
     * @param operatetime the value for ts_sys_operatelog.OperateTime
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setOperatetime(Date operatetime) {
        this.operatetime = operatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_operatelog.CreateBy
     *
     * @return the value of ts_sys_operatelog.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_operatelog.CreateBy
     *
     * @param createby the value for ts_sys_operatelog.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_operatelog.CreateDate
     *
     * @return the value of ts_sys_operatelog.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_operatelog.CreateDate
     *
     * @param createdate the value for ts_sys_operatelog.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}