package org.campus.model;

import java.util.Date;

import org.campus.model.enums.CheckType;

public class PostsCheck {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_posts_check.UID
     *
     * @mbggenerated Wed Aug 19 16:26:59 CST 2015
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_posts_check.PostId
     *
     * @mbggenerated Wed Aug 19 16:26:59 CST 2015
     */
    private String postid;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_posts_check.UserId
     *
     * @mbggenerated Wed Aug 19 16:26:59 CST 2015
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_posts_check.CheckTime
     *
     * @mbggenerated Wed Aug 19 16:26:59 CST 2015
     */
    private Date checktime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_posts_check.CheckType
     *
     * @mbggenerated Wed Aug 19 16:26:59 CST 2015
     */
    private CheckType checktype;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_posts_check.UID
     *
     * @return the value of ts_app_posts_check.UID
     *
     * @mbggenerated Wed Aug 19 16:26:59 CST 2015
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_posts_check.UID
     *
     * @param uid the value for ts_app_posts_check.UID
     *
     * @mbggenerated Wed Aug 19 16:26:59 CST 2015
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_posts_check.PostId
     *
     * @return the value of ts_app_posts_check.PostId
     *
     * @mbggenerated Wed Aug 19 16:26:59 CST 2015
     */
    public String getPostid() {
        return postid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_posts_check.PostId
     *
     * @param postid the value for ts_app_posts_check.PostId
     *
     * @mbggenerated Wed Aug 19 16:26:59 CST 2015
     */
    public void setPostid(String postid) {
        this.postid = postid == null ? null : postid.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_posts_check.UserId
     *
     * @return the value of ts_app_posts_check.UserId
     *
     * @mbggenerated Wed Aug 19 16:26:59 CST 2015
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_posts_check.UserId
     *
     * @param userid the value for ts_app_posts_check.UserId
     *
     * @mbggenerated Wed Aug 19 16:26:59 CST 2015
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_posts_check.CheckTime
     *
     * @return the value of ts_app_posts_check.CheckTime
     *
     * @mbggenerated Wed Aug 19 16:26:59 CST 2015
     */
    public Date getChecktime() {
        return checktime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_posts_check.CheckTime
     *
     * @param checktime the value for ts_app_posts_check.CheckTime
     *
     * @mbggenerated Wed Aug 19 16:26:59 CST 2015
     */
    public void setChecktime(Date checktime) {
        this.checktime = checktime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_posts_check.CheckType
     *
     * @return the value of ts_app_posts_check.CheckType
     *
     * @mbggenerated Wed Aug 19 16:26:59 CST 2015
     */
    public CheckType getChecktype() {
        return checktype;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_posts_check.CheckType
     *
     * @param checktype the value for ts_app_posts_check.CheckType
     *
     * @mbggenerated Wed Aug 19 16:26:59 CST 2015
     */
    public void setChecktype(CheckType checktype) {
        this.checktype = checktype;
    }
}