package org.campus.model;

import java.util.Date;

public class PushMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_pushmessage.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_pushmessage.SourceUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String sourceuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_pushmessage.SendUserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String senduseruid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_pushmessage.ReceiveUserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String receiveuseruid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_pushmessage.GroupUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String groupuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_pushmessage.Alert
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String alert;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_pushmessage.Completepushtime
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Date completepushtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_pushmessage.Pushcount
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Integer pushcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_pushmessage.TypeCode
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Integer typecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_pushmessage.Responsecode
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String responsecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_pushmessage.Responsecontent
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String responsecontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_pushmessage.ErrorCode
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String errorcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_pushmessage.ErrorMsg
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String errormsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_pushmessage.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_pushmessage.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Date createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_pushmessage.UID
     *
     * @return the value of ts_app_pushmessage.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_pushmessage.UID
     *
     * @param uid the value for ts_app_pushmessage.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_pushmessage.SourceUID
     *
     * @return the value of ts_app_pushmessage.SourceUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getSourceuid() {
        return sourceuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_pushmessage.SourceUID
     *
     * @param sourceuid the value for ts_app_pushmessage.SourceUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setSourceuid(String sourceuid) {
        this.sourceuid = sourceuid == null ? null : sourceuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_pushmessage.SendUserUID
     *
     * @return the value of ts_app_pushmessage.SendUserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getSenduseruid() {
        return senduseruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_pushmessage.SendUserUID
     *
     * @param senduseruid the value for ts_app_pushmessage.SendUserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setSenduseruid(String senduseruid) {
        this.senduseruid = senduseruid == null ? null : senduseruid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_pushmessage.ReceiveUserUID
     *
     * @return the value of ts_app_pushmessage.ReceiveUserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getReceiveuseruid() {
        return receiveuseruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_pushmessage.ReceiveUserUID
     *
     * @param receiveuseruid the value for ts_app_pushmessage.ReceiveUserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setReceiveuseruid(String receiveuseruid) {
        this.receiveuseruid = receiveuseruid == null ? null : receiveuseruid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_pushmessage.GroupUID
     *
     * @return the value of ts_app_pushmessage.GroupUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getGroupuid() {
        return groupuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_pushmessage.GroupUID
     *
     * @param groupuid the value for ts_app_pushmessage.GroupUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setGroupuid(String groupuid) {
        this.groupuid = groupuid == null ? null : groupuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_pushmessage.Alert
     *
     * @return the value of ts_app_pushmessage.Alert
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getAlert() {
        return alert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_pushmessage.Alert
     *
     * @param alert the value for ts_app_pushmessage.Alert
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setAlert(String alert) {
        this.alert = alert == null ? null : alert.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_pushmessage.Completepushtime
     *
     * @return the value of ts_app_pushmessage.Completepushtime
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Date getCompletepushtime() {
        return completepushtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_pushmessage.Completepushtime
     *
     * @param completepushtime the value for ts_app_pushmessage.Completepushtime
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCompletepushtime(Date completepushtime) {
        this.completepushtime = completepushtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_pushmessage.Pushcount
     *
     * @return the value of ts_app_pushmessage.Pushcount
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Integer getPushcount() {
        return pushcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_pushmessage.Pushcount
     *
     * @param pushcount the value for ts_app_pushmessage.Pushcount
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setPushcount(Integer pushcount) {
        this.pushcount = pushcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_pushmessage.TypeCode
     *
     * @return the value of ts_app_pushmessage.TypeCode
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Integer getTypecode() {
        return typecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_pushmessage.TypeCode
     *
     * @param typecode the value for ts_app_pushmessage.TypeCode
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setTypecode(Integer typecode) {
        this.typecode = typecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_pushmessage.Responsecode
     *
     * @return the value of ts_app_pushmessage.Responsecode
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getResponsecode() {
        return responsecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_pushmessage.Responsecode
     *
     * @param responsecode the value for ts_app_pushmessage.Responsecode
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setResponsecode(String responsecode) {
        this.responsecode = responsecode == null ? null : responsecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_pushmessage.Responsecontent
     *
     * @return the value of ts_app_pushmessage.Responsecontent
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getResponsecontent() {
        return responsecontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_pushmessage.Responsecontent
     *
     * @param responsecontent the value for ts_app_pushmessage.Responsecontent
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setResponsecontent(String responsecontent) {
        this.responsecontent = responsecontent == null ? null : responsecontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_pushmessage.ErrorCode
     *
     * @return the value of ts_app_pushmessage.ErrorCode
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getErrorcode() {
        return errorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_pushmessage.ErrorCode
     *
     * @param errorcode the value for ts_app_pushmessage.ErrorCode
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setErrorcode(String errorcode) {
        this.errorcode = errorcode == null ? null : errorcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_pushmessage.ErrorMsg
     *
     * @return the value of ts_app_pushmessage.ErrorMsg
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getErrormsg() {
        return errormsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_pushmessage.ErrorMsg
     *
     * @param errormsg the value for ts_app_pushmessage.ErrorMsg
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setErrormsg(String errormsg) {
        this.errormsg = errormsg == null ? null : errormsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_pushmessage.CreateBy
     *
     * @return the value of ts_app_pushmessage.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_pushmessage.CreateBy
     *
     * @param createby the value for ts_app_pushmessage.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_pushmessage.CreateDate
     *
     * @return the value of ts_app_pushmessage.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_pushmessage.CreateDate
     *
     * @param createdate the value for ts_app_pushmessage.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}