package org.campus.model;

import java.util.Date;

public class RetrievemmRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_retrievemmrecord.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_retrievemmrecord.Account
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_retrievemmrecord.Email
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_retrievemmrecord.Updatekey
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String updatekey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_retrievemmrecord.MD5Updatekey
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String md5updatekey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_retrievemmrecord.SendTime
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Date sendtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_retrievemmrecord.CompleteTime
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Date completetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_retrievemmrecord.IsUpdate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Integer isupdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_retrievemmrecord.UID
     *
     * @return the value of ts_sys_retrievemmrecord.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_retrievemmrecord.UID
     *
     * @param uid the value for ts_sys_retrievemmrecord.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_retrievemmrecord.Account
     *
     * @return the value of ts_sys_retrievemmrecord.Account
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_retrievemmrecord.Account
     *
     * @param account the value for ts_sys_retrievemmrecord.Account
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_retrievemmrecord.Email
     *
     * @return the value of ts_sys_retrievemmrecord.Email
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_retrievemmrecord.Email
     *
     * @param email the value for ts_sys_retrievemmrecord.Email
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_retrievemmrecord.Updatekey
     *
     * @return the value of ts_sys_retrievemmrecord.Updatekey
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getUpdatekey() {
        return updatekey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_retrievemmrecord.Updatekey
     *
     * @param updatekey the value for ts_sys_retrievemmrecord.Updatekey
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setUpdatekey(String updatekey) {
        this.updatekey = updatekey == null ? null : updatekey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_retrievemmrecord.MD5Updatekey
     *
     * @return the value of ts_sys_retrievemmrecord.MD5Updatekey
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getMd5updatekey() {
        return md5updatekey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_retrievemmrecord.MD5Updatekey
     *
     * @param md5updatekey the value for ts_sys_retrievemmrecord.MD5Updatekey
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setMd5updatekey(String md5updatekey) {
        this.md5updatekey = md5updatekey == null ? null : md5updatekey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_retrievemmrecord.SendTime
     *
     * @return the value of ts_sys_retrievemmrecord.SendTime
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Date getSendtime() {
        return sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_retrievemmrecord.SendTime
     *
     * @param sendtime the value for ts_sys_retrievemmrecord.SendTime
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setSendtime(Date sendtime) {
        this.sendtime = sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_retrievemmrecord.CompleteTime
     *
     * @return the value of ts_sys_retrievemmrecord.CompleteTime
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Date getCompletetime() {
        return completetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_retrievemmrecord.CompleteTime
     *
     * @param completetime the value for ts_sys_retrievemmrecord.CompleteTime
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCompletetime(Date completetime) {
        this.completetime = completetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_retrievemmrecord.IsUpdate
     *
     * @return the value of ts_sys_retrievemmrecord.IsUpdate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Integer getIsupdate() {
        return isupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_retrievemmrecord.IsUpdate
     *
     * @param isupdate the value for ts_sys_retrievemmrecord.IsUpdate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setIsupdate(Integer isupdate) {
        this.isupdate = isupdate;
    }
}