package org.campus.model;

import java.util.Date;

public class Session {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_session.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_session.UserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String useruid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_session.ObjUserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String objuseruid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_session.LastMsgContent
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String lastmsgcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_session.TypeCode
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Integer typecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_session.LastMessageTime
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Date lastmessagetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_session.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_session.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Date createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_session.UID
     *
     * @return the value of ts_app_session.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_session.UID
     *
     * @param uid the value for ts_app_session.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_session.UserUID
     *
     * @return the value of ts_app_session.UserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getUseruid() {
        return useruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_session.UserUID
     *
     * @param useruid the value for ts_app_session.UserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setUseruid(String useruid) {
        this.useruid = useruid == null ? null : useruid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_session.ObjUserUID
     *
     * @return the value of ts_app_session.ObjUserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getObjuseruid() {
        return objuseruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_session.ObjUserUID
     *
     * @param objuseruid the value for ts_app_session.ObjUserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setObjuseruid(String objuseruid) {
        this.objuseruid = objuseruid == null ? null : objuseruid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_session.LastMsgContent
     *
     * @return the value of ts_app_session.LastMsgContent
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getLastmsgcontent() {
        return lastmsgcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_session.LastMsgContent
     *
     * @param lastmsgcontent the value for ts_app_session.LastMsgContent
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setLastmsgcontent(String lastmsgcontent) {
        this.lastmsgcontent = lastmsgcontent == null ? null : lastmsgcontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_session.TypeCode
     *
     * @return the value of ts_app_session.TypeCode
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Integer getTypecode() {
        return typecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_session.TypeCode
     *
     * @param typecode the value for ts_app_session.TypeCode
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setTypecode(Integer typecode) {
        this.typecode = typecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_session.LastMessageTime
     *
     * @return the value of ts_app_session.LastMessageTime
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Date getLastmessagetime() {
        return lastmessagetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_session.LastMessageTime
     *
     * @param lastmessagetime the value for ts_app_session.LastMessageTime
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setLastmessagetime(Date lastmessagetime) {
        this.lastmessagetime = lastmessagetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_session.CreateBy
     *
     * @return the value of ts_app_session.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_session.CreateBy
     *
     * @param createby the value for ts_app_session.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_session.CreateDate
     *
     * @return the value of ts_app_session.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_session.CreateDate
     *
     * @param createdate the value for ts_app_session.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}