package org.campus.model;

import java.util.Date;

import org.campus.model.enums.ActiveType;

public class Share {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column ts_app_share.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_share.ActivityUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String activityuid;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_share.ShareUserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String shareuseruid;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_share.ShareTime
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Date sharetime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_share.FreshNewsUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String freshnewsuid;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_share.isActive
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private ActiveType isactive;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_share.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_share.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_share.LastUpdateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String lastupdateby;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_share.LastUpdateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Date lastupdatedate;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_share.UID
     *
     * @return the value of ts_app_share.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_share.UID
     *
     * @param uid the value for ts_app_share.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_share.ActivityUID
     *
     * @return the value of ts_app_share.ActivityUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getActivityuid() {
        return activityuid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_share.ActivityUID
     *
     * @param activityuid the value for ts_app_share.ActivityUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setActivityuid(String activityuid) {
        this.activityuid = activityuid == null ? null : activityuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_share.ShareUserUID
     *
     * @return the value of ts_app_share.ShareUserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getShareuseruid() {
        return shareuseruid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_share.ShareUserUID
     *
     * @param shareuseruid the value for ts_app_share.ShareUserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setShareuseruid(String shareuseruid) {
        this.shareuseruid = shareuseruid == null ? null : shareuseruid.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_share.ShareTime
     *
     * @return the value of ts_app_share.ShareTime
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Date getSharetime() {
        return sharetime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_share.ShareTime
     *
     * @param sharetime the value for ts_app_share.ShareTime
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setSharetime(Date sharetime) {
        this.sharetime = sharetime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_share.FreshNewsUID
     *
     * @return the value of ts_app_share.FreshNewsUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getFreshnewsuid() {
        return freshnewsuid;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_share.FreshNewsUID
     *
     * @param freshnewsuid the value for ts_app_share.FreshNewsUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setFreshnewsuid(String freshnewsuid) {
        this.freshnewsuid = freshnewsuid == null ? null : freshnewsuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_share.isActive
     *
     * @return the value of ts_app_share.isActive
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public ActiveType getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_share.isActive
     *
     * @param isactive the value for ts_app_share.isActive
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setIsactive(ActiveType isactive) {
        this.isactive = isactive;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_share.CreateBy
     *
     * @return the value of ts_app_share.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_share.CreateBy
     *
     * @param createby the value for ts_app_share.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_share.CreateDate
     *
     * @return the value of ts_app_share.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_share.CreateDate
     *
     * @param createdate the value for ts_app_share.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_share.LastUpdateBy
     *
     * @return the value of ts_app_share.LastUpdateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getLastupdateby() {
        return lastupdateby;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_share.LastUpdateBy
     *
     * @param lastupdateby the value for ts_app_share.LastUpdateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setLastupdateby(String lastupdateby) {
        this.lastupdateby = lastupdateby == null ? null : lastupdateby.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_share.LastUpdateDate
     *
     * @return the value of ts_app_share.LastUpdateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Date getLastupdatedate() {
        return lastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_share.LastUpdateDate
     *
     * @param lastupdatedate the value for ts_app_share.LastUpdateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setLastupdatedate(Date lastupdatedate) {
        this.lastupdatedate = lastupdatedate;
    }
}