package org.campus.model;

import java.util.Date;

public class Signin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_signin.UID
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_signin.UserId
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_signin.LoginDate
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    private Date logindate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_signin.UID
     *
     * @return the value of ts_app_signin.UID
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_signin.UID
     *
     * @param uid the value for ts_app_signin.UID
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_signin.UserId
     *
     * @return the value of ts_app_signin.UserId
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_signin.UserId
     *
     * @param userid the value for ts_app_signin.UserId
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_signin.LoginDate
     *
     * @return the value of ts_app_signin.LoginDate
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    public Date getLogindate() {
        return logindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_signin.LoginDate
     *
     * @param logindate the value for ts_app_signin.LoginDate
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    public void setLogindate(Date logindate) {
        this.logindate = logindate;
    }
}