package org.campus.model;

import java.util.Date;

import org.campus.model.enums.SMSResult;
import org.campus.model.enums.SMSType;

public class SmsRecord {

    private String uid;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_smsrecord.PhoneNumber
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String phonenumber;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_smsrecord.ValidateCode
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String validatecode;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_smsrecord.SMSMsg
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String smsmsg;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_smsrecord.SMSType
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private SMSType smstype;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_smsrecord.Expire
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Integer expire;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_smsrecord.SendTime
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Date sendtime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_smsrecord.CompleteTime
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Date completetime;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_smsrecord.IsSuccess
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private SMSResult issuccess;

    private String resultMsg;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_smsrecord.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column
     * ts_app_smsrecord.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Date createdate;

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_smsrecord.PhoneNumber
     *
     * @return the value of ts_app_smsrecord.PhoneNumber
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_smsrecord.PhoneNumber
     *
     * @param phonenumber the value for ts_app_smsrecord.PhoneNumber
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setPhonenumber(String phonenumber) {
        this.phonenumber = phonenumber == null ? null : phonenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_smsrecord.ValidateCode
     *
     * @return the value of ts_app_smsrecord.ValidateCode
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getValidatecode() {
        return validatecode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_smsrecord.ValidateCode
     *
     * @param validatecode the value for ts_app_smsrecord.ValidateCode
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setValidatecode(String validatecode) {
        this.validatecode = validatecode == null ? null : validatecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_smsrecord.SMSMsg
     *
     * @return the value of ts_app_smsrecord.SMSMsg
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getSmsmsg() {
        return smsmsg;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_smsrecord.SMSMsg
     *
     * @param smsmsg the value for ts_app_smsrecord.SMSMsg
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setSmsmsg(String smsmsg) {
        this.smsmsg = smsmsg == null ? null : smsmsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_smsrecord.SMSType
     *
     * @return the value of ts_app_smsrecord.SMSType
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public SMSType getSmstype() {
        return smstype;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_smsrecord.SMSType
     *
     * @param smstype the value for ts_app_smsrecord.SMSType
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setSmstype(SMSType smstype) {
        this.smstype = smstype;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_smsrecord.Expire
     *
     * @return the value of ts_app_smsrecord.Expire
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Integer getExpire() {
        return expire;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_smsrecord.Expire
     *
     * @param expire the value for ts_app_smsrecord.Expire
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setExpire(Integer expire) {
        this.expire = expire;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_smsrecord.SendTime
     *
     * @return the value of ts_app_smsrecord.SendTime
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Date getSendtime() {
        return sendtime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_smsrecord.SendTime
     *
     * @param sendtime the value for ts_app_smsrecord.SendTime
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setSendtime(Date sendtime) {
        this.sendtime = sendtime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_smsrecord.CompleteTime
     *
     * @return the value of ts_app_smsrecord.CompleteTime
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Date getCompletetime() {
        return completetime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_smsrecord.CompleteTime
     *
     * @param completetime the value for ts_app_smsrecord.CompleteTime
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCompletetime(Date completetime) {
        this.completetime = completetime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_smsrecord.IsSuccess
     *
     * @return the value of ts_app_smsrecord.IsSuccess
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public SMSResult getIssuccess() {
        return issuccess;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_smsrecord.IsSuccess
     *
     * @param issuccess the value for ts_app_smsrecord.IsSuccess
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setIssuccess(SMSResult issuccess) {
        this.issuccess = issuccess;
    }

    public String getResultMsg() {
        return resultMsg;
    }

    public void setResultMsg(String resultMsg) {
        this.resultMsg = resultMsg;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_smsrecord.CreateBy
     *
     * @return the value of ts_app_smsrecord.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_smsrecord.CreateBy
     *
     * @param createby the value for ts_app_smsrecord.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column
     * ts_app_smsrecord.CreateDate
     *
     * @return the value of ts_app_smsrecord.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column
     * ts_app_smsrecord.CreateDate
     *
     * @param createdate the value for ts_app_smsrecord.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}