package org.campus.model;

import java.util.Date;

public class SysUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_user.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_user.UserAccount
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String useraccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_user.UserPwd
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String userpwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_user.RoleUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String roleuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_user.IsCheck
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Integer ischeck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_user.CheckUserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String checkuseruid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_user.CheckTime
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Date checktime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_user.CheckRemark
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String checkremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_user.LastLoginTime
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Date lastlogintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_user.SignId
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String signid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_user.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_user.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_user.IsActive
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Integer isactive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_user.LastUpdateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String lastupdateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_sys_user.LastUpdateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Date lastupdatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_user.UID
     *
     * @return the value of ts_sys_user.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_user.UID
     *
     * @param uid the value for ts_sys_user.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_user.UserAccount
     *
     * @return the value of ts_sys_user.UserAccount
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getUseraccount() {
        return useraccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_user.UserAccount
     *
     * @param useraccount the value for ts_sys_user.UserAccount
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setUseraccount(String useraccount) {
        this.useraccount = useraccount == null ? null : useraccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_user.UserPwd
     *
     * @return the value of ts_sys_user.UserPwd
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getUserpwd() {
        return userpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_user.UserPwd
     *
     * @param userpwd the value for ts_sys_user.UserPwd
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setUserpwd(String userpwd) {
        this.userpwd = userpwd == null ? null : userpwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_user.RoleUID
     *
     * @return the value of ts_sys_user.RoleUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getRoleuid() {
        return roleuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_user.RoleUID
     *
     * @param roleuid the value for ts_sys_user.RoleUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setRoleuid(String roleuid) {
        this.roleuid = roleuid == null ? null : roleuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_user.IsCheck
     *
     * @return the value of ts_sys_user.IsCheck
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Integer getIscheck() {
        return ischeck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_user.IsCheck
     *
     * @param ischeck the value for ts_sys_user.IsCheck
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setIscheck(Integer ischeck) {
        this.ischeck = ischeck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_user.CheckUserUID
     *
     * @return the value of ts_sys_user.CheckUserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getCheckuseruid() {
        return checkuseruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_user.CheckUserUID
     *
     * @param checkuseruid the value for ts_sys_user.CheckUserUID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCheckuseruid(String checkuseruid) {
        this.checkuseruid = checkuseruid == null ? null : checkuseruid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_user.CheckTime
     *
     * @return the value of ts_sys_user.CheckTime
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Date getChecktime() {
        return checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_user.CheckTime
     *
     * @param checktime the value for ts_sys_user.CheckTime
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setChecktime(Date checktime) {
        this.checktime = checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_user.CheckRemark
     *
     * @return the value of ts_sys_user.CheckRemark
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getCheckremark() {
        return checkremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_user.CheckRemark
     *
     * @param checkremark the value for ts_sys_user.CheckRemark
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCheckremark(String checkremark) {
        this.checkremark = checkremark == null ? null : checkremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_user.LastLoginTime
     *
     * @return the value of ts_sys_user.LastLoginTime
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Date getLastlogintime() {
        return lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_user.LastLoginTime
     *
     * @param lastlogintime the value for ts_sys_user.LastLoginTime
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setLastlogintime(Date lastlogintime) {
        this.lastlogintime = lastlogintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_user.SignId
     *
     * @return the value of ts_sys_user.SignId
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getSignid() {
        return signid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_user.SignId
     *
     * @param signid the value for ts_sys_user.SignId
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setSignid(String signid) {
        this.signid = signid == null ? null : signid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_user.CreateBy
     *
     * @return the value of ts_sys_user.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_user.CreateBy
     *
     * @param createby the value for ts_sys_user.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_user.CreateDate
     *
     * @return the value of ts_sys_user.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_user.CreateDate
     *
     * @param createdate the value for ts_sys_user.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_user.IsActive
     *
     * @return the value of ts_sys_user.IsActive
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Integer getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_user.IsActive
     *
     * @param isactive the value for ts_sys_user.IsActive
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setIsactive(Integer isactive) {
        this.isactive = isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_user.LastUpdateBy
     *
     * @return the value of ts_sys_user.LastUpdateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getLastupdateby() {
        return lastupdateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_user.LastUpdateBy
     *
     * @param lastupdateby the value for ts_sys_user.LastUpdateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setLastupdateby(String lastupdateby) {
        this.lastupdateby = lastupdateby == null ? null : lastupdateby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_sys_user.LastUpdateDate
     *
     * @return the value of ts_sys_user.LastUpdateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Date getLastupdatedate() {
        return lastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_sys_user.LastUpdateDate
     *
     * @param lastupdatedate the value for ts_sys_user.LastUpdateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setLastupdatedate(Date lastupdatedate) {
        this.lastupdatedate = lastupdatedate;
    }
}