package org.campus.model;

import java.math.BigDecimal;
import java.util.Date;

public class Version {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_version.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_version.TypeCode
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Integer typecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_version.VersionNum
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private BigDecimal versionnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_version.Url
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_version.IsActive
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Integer isactive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_version.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_version.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_version.LastUpdateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private String lastupdateby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_app_version.LastUpdateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    private Date lastupdatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_version.UID
     *
     * @return the value of ts_app_version.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_version.UID
     *
     * @param uid the value for ts_app_version.UID
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_version.TypeCode
     *
     * @return the value of ts_app_version.TypeCode
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Integer getTypecode() {
        return typecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_version.TypeCode
     *
     * @param typecode the value for ts_app_version.TypeCode
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setTypecode(Integer typecode) {
        this.typecode = typecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_version.VersionNum
     *
     * @return the value of ts_app_version.VersionNum
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public BigDecimal getVersionnum() {
        return versionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_version.VersionNum
     *
     * @param versionnum the value for ts_app_version.VersionNum
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setVersionnum(BigDecimal versionnum) {
        this.versionnum = versionnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_version.Url
     *
     * @return the value of ts_app_version.Url
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_version.Url
     *
     * @param url the value for ts_app_version.Url
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_version.IsActive
     *
     * @return the value of ts_app_version.IsActive
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Integer getIsactive() {
        return isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_version.IsActive
     *
     * @param isactive the value for ts_app_version.IsActive
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setIsactive(Integer isactive) {
        this.isactive = isactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_version.CreateBy
     *
     * @return the value of ts_app_version.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_version.CreateBy
     *
     * @param createby the value for ts_app_version.CreateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_version.CreateDate
     *
     * @return the value of ts_app_version.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_version.CreateDate
     *
     * @param createdate the value for ts_app_version.CreateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_version.LastUpdateBy
     *
     * @return the value of ts_app_version.LastUpdateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public String getLastupdateby() {
        return lastupdateby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_version.LastUpdateBy
     *
     * @param lastupdateby the value for ts_app_version.LastUpdateBy
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setLastupdateby(String lastupdateby) {
        this.lastupdateby = lastupdateby == null ? null : lastupdateby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_app_version.LastUpdateDate
     *
     * @return the value of ts_app_version.LastUpdateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public Date getLastupdatedate() {
        return lastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_app_version.LastUpdateDate
     *
     * @param lastupdatedate the value for ts_app_version.LastUpdateDate
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    public void setLastupdatedate(Date lastupdatedate) {
        this.lastupdatedate = lastupdatedate;
    }
}