package org.campus.repository;

import org.campus.model.AppealInfo;
import org.springframework.stereotype.Repository;

@Repository
public interface AppealInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_appealinfo
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int deleteByPrimaryKey(String appealuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_appealinfo
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int insert(AppealInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_appealinfo
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int insertSelective(AppealInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_appealinfo
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    AppealInfo selectByPrimaryKey(String appealuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_appealinfo
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int updateByPrimaryKeySelective(AppealInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_appealinfo
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int updateByPrimaryKey(AppealInfo record);
}