package org.campus.repository;

import org.apache.ibatis.annotations.Param;
import org.campus.model.AttentionUser;
import org.springframework.stereotype.Repository;

@Repository
public interface AttentionUserMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * ts_app_attentionuser
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int deleteByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * ts_app_attentionuser
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int insert(AttentionUser record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * ts_app_attentionuser
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int insertSelective(AttentionUser record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * ts_app_attentionuser
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    AttentionUser selectByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * ts_app_attentionuser
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int updateByPrimaryKeySelective(AttentionUser record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * ts_app_attentionuser
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int updateByPrimaryKey(AttentionUser record);

    int countAttention(String userId);

    int countFans(String userId);

    int removeAttention(@Param("comUserId") String comUserId, @Param("objUserId") String objUserId);

    void deleteByMyUserId(String userId);

}