package org.campus.repository;

import org.campus.model.Category;
import org.springframework.stereotype.Repository;

@Repository
public interface CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_sys_category
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_sys_category
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int insertSelective(Category record);
}