package org.campus.repository;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.campus.model.Comment;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Repository;

@Repository
public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ts_app_comment
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int deleteByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ts_app_comment
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ts_app_comment
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int insertSelective(Comment record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ts_app_comment
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    Comment selectByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ts_app_comment
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int updateByPrimaryKeySelective(Comment record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ts_app_comment
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int updateByPrimaryKey(Comment record);

    Page<Comment> findBySourceId(@Param("sourceId") String sourceId, Pageable pageable);

    void deleteAll();

    List<Comment> findMyComments(@Param("sourceId") String sourceId, @Param("userId") String userId);

}