package org.campus.repository;

import org.campus.model.Complain;
import org.springframework.stereotype.Repository;

@Repository
public interface ComplainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_complain
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int deleteByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_complain
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int insert(Complain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_complain
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int insertSelective(Complain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_complain
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    Complain selectByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_complain
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int updateByPrimaryKeySelective(Complain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_complain
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int updateByPrimaryKey(Complain record);
}