package org.campus.repository;

import org.campus.model.Install;
import org.springframework.stereotype.Repository;

@Repository
public interface InstallMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ts_app_install
     *
     * @mbggenerated Tue Aug 25 23:41:54 CST 2015
     */
    int insert(Install record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ts_app_install
     *
     * @mbggenerated Tue Aug 25 23:41:54 CST 2015
     */
    int insertSelective(Install record);
}