package org.campus.repository;

import org.campus.model.Integral;
import org.springframework.stereotype.Repository;

@Repository
public interface IntegralMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ts_app_integral
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    int deleteByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ts_app_integral
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    int insert(Integral record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ts_app_integral
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    int insertSelective(Integral record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ts_app_integral
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    Integral selectByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ts_app_integral
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    int updateByPrimaryKeySelective(Integral record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ts_app_integral
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    int updateByPrimaryKey(Integral record);
}