package org.campus.repository;

import org.campus.model.LogType;
import org.springframework.stereotype.Repository;

@Repository
public interface LogTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_sys_logtype
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int deleteByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_sys_logtype
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int insert(LogType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_sys_logtype
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int insertSelective(LogType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_sys_logtype
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    LogType selectByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_sys_logtype
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int updateByPrimaryKeySelective(LogType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_sys_logtype
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int updateByPrimaryKey(LogType record);
}