package org.campus.repository;

import org.campus.model.MessageGroup;
import org.springframework.stereotype.Repository;

@Repository
public interface MessageGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_messagegroup
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int deleteByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_messagegroup
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int insert(MessageGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_messagegroup
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int insertSelective(MessageGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_messagegroup
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    MessageGroup selectByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_messagegroup
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int updateByPrimaryKeySelective(MessageGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_messagegroup
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int updateByPrimaryKey(MessageGroup record);
}