package org.campus.repository;

import org.campus.model.NickName;
import org.springframework.stereotype.Repository;

@Repository
public interface NickNameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_nickname
     *
     * @mbggenerated Thu Aug 13 16:29:19 CST 2015
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_nickname
     *
     * @mbggenerated Thu Aug 13 16:29:19 CST 2015
     */
    int insert(NickName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_nickname
     *
     * @mbggenerated Thu Aug 13 16:29:19 CST 2015
     */
    int insertSelective(NickName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_nickname
     *
     * @mbggenerated Thu Aug 13 16:29:19 CST 2015
     */
    NickName selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_nickname
     *
     * @mbggenerated Thu Aug 13 16:29:19 CST 2015
     */
    int updateByPrimaryKeySelective(NickName record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_nickname
     *
     * @mbggenerated Thu Aug 13 16:29:19 CST 2015
     */
    int updateByPrimaryKey(NickName record);
    
    void deleteAll();
    
    int count();
    
}