package org.campus.repository;

import org.apache.ibatis.annotations.Param;
import org.campus.model.NotSupport;
import org.springframework.stereotype.Repository;

@Repository
public interface NotSupportMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ts_app_notsupport
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int deleteByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ts_app_notsupport
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int insert(NotSupport record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ts_app_notsupport
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int insertSelective(NotSupport record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ts_app_notsupport
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    NotSupport selectByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ts_app_notsupport
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int updateByPrimaryKeySelective(NotSupport record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ts_app_notsupport
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int updateByPrimaryKey(NotSupport record);

    void deleteAll();
    
    void delete(@Param("sourceId") String sourceId, @Param("userId") String userId);

}