package org.campus.repository;

import org.campus.model.Partake;
import org.springframework.stereotype.Repository;

@Repository
public interface PartakeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_partake
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int deleteByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_partake
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int insert(Partake record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_partake
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int insertSelective(Partake record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_partake
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    Partake selectByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_partake
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int updateByPrimaryKeySelective(Partake record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_partake
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int updateByPrimaryKey(Partake record);
}