package org.campus.repository;

import org.campus.model.PushMessage;
import org.springframework.stereotype.Repository;

@Repository
public interface PushMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_pushmessage
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int deleteByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_pushmessage
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int insert(PushMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_pushmessage
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int insertSelective(PushMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_pushmessage
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    PushMessage selectByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_pushmessage
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int updateByPrimaryKeySelective(PushMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_pushmessage
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int updateByPrimaryKey(PushMessage record);
}