package org.campus.repository;

import java.util.Date;

import org.apache.ibatis.annotations.Param;
import org.campus.model.Signin;
import org.springframework.stereotype.Repository;

@Repository
public interface SigninMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ts_app_signin
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    int deleteByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ts_app_signin
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    int insert(Signin record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ts_app_signin
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    int insertSelective(Signin record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ts_app_signin
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    Signin selectByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ts_app_signin
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    int updateByPrimaryKeySelective(Signin record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ts_app_signin
     *
     * @mbggenerated Tue Aug 18 15:57:38 CST 2015
     */
    int updateByPrimaryKey(Signin record);

    Signin findDayByUserId(@Param("userId") String userId, @Param("date") Date date);

}