package org.campus.repository;

import org.campus.model.SmsRecord;
import org.springframework.stereotype.Repository;

@Repository
public interface SmsRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_smsrecord
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int deleteByPrimaryKey(String phonenumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_smsrecord
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int insert(SmsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_smsrecord
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int insertSelective(SmsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_smsrecord
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    SmsRecord selectByPrimaryKey(String phonenumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_smsrecord
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int updateByPrimaryKeySelective(SmsRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ts_app_smsrecord
     *
     * @mbggenerated Sun Aug 09 23:25:01 CST 2015
     */
    int updateByPrimaryKey(SmsRecord record);
}