package org.campus.repository;

import org.campus.model.Transfer;
import org.springframework.stereotype.Repository;

@Repository
public interface TransferMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ts_app_transfer
     *
     * @mbggenerated Wed Aug 26 00:06:18 CST 2015
     */
    int deleteByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ts_app_transfer
     *
     * @mbggenerated Wed Aug 26 00:06:18 CST 2015
     */
    int insert(Transfer record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ts_app_transfer
     *
     * @mbggenerated Wed Aug 26 00:06:18 CST 2015
     */
    int insertSelective(Transfer record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ts_app_transfer
     *
     * @mbggenerated Wed Aug 26 00:06:18 CST 2015
     */
    Transfer selectByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ts_app_transfer
     *
     * @mbggenerated Wed Aug 26 00:06:18 CST 2015
     */
    int updateByPrimaryKeySelective(Transfer record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table ts_app_transfer
     *
     * @mbggenerated Wed Aug 26 00:06:18 CST 2015
     */
    int updateByPrimaryKey(Transfer record);
    
    Transfer findTransferByObjPostId(String postId);
    
}